const fs = require('fs');
let html = fs.readFileSync('dist/index.html', 'utf8');
html = html.replace('<html lang="en">', '<html lang="fr">');
html = html.replace('shrink-to-fit=no"', 'shrink-to-fit=no, viewport-fit=cover"');
const meta = [
  '    <meta name="theme-color" content="#12161c" />',
  '    <meta name="apple-mobile-web-app-capable" content="yes" />',
  '    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />',
  '    <meta name="apple-mobile-web-app-title" content="ObsiRAG" />',
  '    <meta name="application-name" content="ObsiRAG" />',
  '    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />',
].join('\n');
html = html.replace('<title>ObsiRAG</title>', meta + '\n    <title>ObsiRAG</title>');

const standaloneStyle = [
  '    <style id="obsirag-standalone-fixes">',
  '      :root { --obsirag-app-height: 100dvh; }',
  '      html, body, #root { min-height: 100%; }',
  '      html[data-obsirag-standalone="true"],',
  '      html[data-obsirag-standalone="true"] body,',
  '      html[data-obsirag-standalone="true"] #root {',
  '        height: var(--obsirag-app-height) !important;',
  '        min-height: var(--obsirag-app-height) !important;',
  '        max-height: var(--obsirag-app-height) !important;',
  '        overflow: hidden !important;',
  '      }',
  '      html[data-obsirag-standalone="true"] [role="tablist"] {',
  '        position: fixed !important;',
  '        left: 0 !important;',
  '        right: 0 !important;',
  '        bottom: 0 !important;',
  '        transform: none !important;',
  '        z-index: 2147483646 !important;',
  '      }',
  '    </style>',
].join('\n');

const standaloneScript = [
  '    <script id="obsirag-standalone-runtime">',
  '      (function () {',
  '        var observer;',
  '        function applyAppHeight() {',
  '          var vv = window.visualViewport;',
  '          var h = Math.round(Math.max(',
  '            window.innerHeight || 0,',
  '            vv && vv.height ? vv.height : 0,',
  '            document.documentElement.clientHeight || 0',
  '          ));',
  '          document.documentElement.style.setProperty("--obsirag-app-height", h + "px");',
  '        }',
  '        function isStandalone() {',
  '          var mode = window.matchMedia && window.matchMedia("(display-mode: standalone)").matches;',
  '          var nav = window.navigator && window.navigator.standalone === true;',
  '          return !!(mode || nav);',
  '        }',
  '        function patchTabBar(standalone) {',
  '          var tablist = document.querySelector("[role=\\"tablist\\"]");',
  '          if (!tablist) return;',
  '          if (!standalone) return;',
  '          tablist.style.position = "fixed";',
  '          tablist.style.left = "0";',
  '          tablist.style.right = "0";',
  '          tablist.style.bottom = "0";',
  '          tablist.style.height = "64px";',
  '          tablist.style.minHeight = "64px";',
  '          tablist.style.maxHeight = "64px";',
  '          tablist.style.paddingTop = "0";',
  '          tablist.style.paddingBottom = "0";',
  '          tablist.style.marginTop = "0";',
  '          tablist.style.marginBottom = "0";',
  '          tablist.style.transform = "none";',
  '          tablist.style.zIndex = "2147483646";',
  '        }',
  '        function ensureObserver(standalone) {',
  '          if (!standalone) {',
  '            if (observer) observer.disconnect();',
  '            observer = undefined;',
  '            return;',
  '          }',
  '          if (observer || typeof MutationObserver === "undefined") return;',
  '          observer = new MutationObserver(function () {',
  '            patchTabBar(true);',
  '          });',
  '          observer.observe(document.documentElement, { childList: true, subtree: true, attributes: true });',
  '        }',
  '        function applyStandaloneFixes() {',
  '          var standalone = isStandalone();',
  '          document.documentElement.setAttribute("data-obsirag-standalone", standalone ? "true" : "false");',
  '          patchTabBar(standalone);',
  '          ensureObserver(standalone);',
  '        }',
  '        applyAppHeight();',
  '        applyStandaloneFixes();',
  '        if (document.readyState === "loading") {',
  '          document.addEventListener("DOMContentLoaded", function () {',
  '            applyAppHeight();',
  '            applyStandaloneFixes();',
  '          }, { once: true });',
  '        }',
  '        requestAnimationFrame(function () {',
  '          applyAppHeight();',
  '          applyStandaloneFixes();',
  '        });',
  '        window.addEventListener("resize", applyAppHeight, { passive: true });',
  '        window.addEventListener("orientationchange", applyAppHeight, { passive: true });',
  '        if (window.visualViewport) {',
  '          window.visualViewport.addEventListener("resize", applyAppHeight, { passive: true });',
  '        }',
  '      })();',
  '    </script>',
].join('\n');

if (!html.includes('id="obsirag-standalone-fixes"')) {
  html = html.replace('</head>', standaloneStyle + '\n' + standaloneScript + '\n  </head>');
}
fs.writeFileSync('dist/index.html', html);
console.log('index.html patché');
